[tool.pydoclint]
style = 'google'
exclude = '\.git|\.tox|tests/data|some_script\.py'
require-return-section-when-returning-nothing = false
skip-checking-short-docstrings = false
arg-type-hints-in-docstring = false
